apiVersion: v1
kind: Service
metadata:
  name: echo-api-svc
  namespace: echo-dev
spec:
  type: ClusterIP
  selector:
    app: echo-api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
