name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./module_2/docker_review
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/echo:latest
            ${{ secrets.DOCKERHUB_USER }}/echo:sha-${{ github.sha }}